### ISSUE TITLE
Support Lumen 5.6

### ISSUE THREAD

**Issue by yoobato** [albertcht/lumen-helpers#1]
I think this helper class will work properly in Lumen framework version 5.6 too.
Please update composer.json to support Lumen 5.6.

Thanks.

**Comment by albertcht** [comment]
Hi @yoobato ,

Thanks for your suggestion, I will update it in the next few days.

**Comment by albertcht** [comment]
Hi @yoobato ,

Now it supports Lumen 5.6 in release v0.3.
